-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.fiis
(
    ticker character(6) COLLATE pg_catalog."default" NOT NULL,
    cnpj character(14) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    segmento_id integer,
    tipo_id integer,
    valor_cota numeric(8, 2),
    dividend_yield numeric(5, 2),
    ffo_yield numeric(5, 2),
    pvp numeric(5, 2),
    liquidez numeric(20, 2),
    valor_mercado numeric(20, 2),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT pk_fiis PRIMARY KEY (ticker)
);

CREATE TABLE IF NOT EXISTS public.fiis_segmentos
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_fiis_segmentos PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fiis_tipos
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(40) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_fiis_tipos PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.fiis
    ADD CONSTRAINT fk_fiis_segmento FOREIGN KEY (segmento_id)
    REFERENCES public.fiis_segmentos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.fiis
    ADD CONSTRAINT fk_fiis_tipo FOREIGN KEY (tipo_id)
    REFERENCES public.fiis_tipos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;
